import '@radix-ui/themes/styles.css';
import "./theme-config.css"
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {Container, Theme} from "@radix-ui/themes"
import NavBar from "@/app/NavBar";

const inter = Inter({
    subsets: ['latin'],
    variable: "--font-inter"
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={inter.variable}>
        <body className={inter.variable}>
        <Theme>
            <Container>
                <NavBar/>
                <main className="p-5">
                    {children}
                </main>
                {/*<ThemePanel/>*/}
            </Container>
        </Theme>
        </body>
        </html>
    )
}
